In [1]:
import numpy as np

A = (np.arange(9) - 4).reshape(3,3)
A

array([[-4, -3, -2],
       [-1,  0,  1],
       [ 2,  3,  4]])

In [2]:
np.linalg.norm(A)

7.745966692414834

In [3]:
np.trace(np.eye(3))

3.0

In [4]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.linalg.det(A)

-9.51619735392994e-16

In [6]:
import numpy as np

A = np.array([[1,1,0], [0,1,1], [1,1,1]])
A

array([[1, 1, 0],
       [0, 1, 1],
       [1, 1, 1]])

In [7]:
Ainv = np.linalg.inv(A)
Ainv

array([[ 0., -1.,  1.],
       [ 1.,  1., -1.],
       [-1.,  0.,  1.]])

In [5]:
#역행렬과 선형연립방정식의 해
b = np.array([[2], [2], [3]])
b

array([[2],
       [2],
       [3]])

In [8]:
x = Ainv@b
x

array([[1.],
       [1.],
       [1.]])

In [9]:
A@x-b

array([[0.],
       [0.],
       [0.]])

In [11]:
#보스턴 집값 문제. 
#범죄율, 공기 오염도, 방의 개수, 오래된 정도 4가지의 특징데이터 4개를 갖는 행렬 A
#우리가 구하려는 건 가중치 벡터 x (스몰 엑스)
#y가 집값.

from sklearn.datasets import load_boston
boston = load_boston()
X = boston.data
y = boston.target
A = X[:4, [0, 4, 5, 6]] #Crim(범죄율), Nox(공기 오염도), RM(방 개수), AGE(오래된 정도)
b = y[:4]

In [12]:
Ainv = np.linalg.inv(A)
x = np.dot(Ainv, b)
print(x)

[-3.12710043e+02 -1.15193942e+02  1.44996465e+01 -1.13259317e-01]


In [13]:
#최소 자승 문제 실전.
#일단은 그냥 한 번 풀어보고 이후이 lstsq 함수 사용해서 풀어서 비교해보기

A = np.array([[1,1,0], [0,1,1], [1,1,1], [1,1,2]])
A

array([[1, 1, 0],
       [0, 1, 1],
       [1, 1, 1],
       [1, 1, 2]])

In [14]:
b = np.array([[2], [2], [3], [4.1]])
b

array([[2. ],
       [2. ],
       [3. ],
       [4.1]])

In [15]:
Apinv = np.linalg.inv(A.T@A)@A.T
Apinv

array([[ 0.33333333, -1.        ,  0.33333333,  0.33333333],
       [ 0.5       ,  1.        ,  0.        , -0.5       ],
       [-0.5       ,  0.        ,  0.        ,  0.5       ]])

In [18]:
x = Apinv@b
x

array([[1.03333333],
       [0.95      ],
       [1.05      ]])

In [19]:
A@x #결과 : b와 굉장히 비슷함.

array([[1.98333333],
       [2.        ],
       [3.03333333],
       [4.08333333]])

In [20]:
#lstsq함수 이용해서 풀어보기.

x, resid, rank, s = np.linalg.lstsq(A, b)
x

<ipython-input-20-d93a57d8ddb3>:3: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  x, resid, rank, s = np.linalg.lstsq(A, b)


array([[1.03333333],
       [0.95      ],
       [1.05      ]])

In [23]:
#보스턴 집값 문제를 최소 자승 문제로, lstsq 함수로 풀기

from sklearn.datasets import load_boston
boston = load_boston()
X = boston.data
y = boston.target

x, resid, rank, s = np.linalg.lstsq(X, y)
print(x)

[-9.28965170e-02  4.87149552e-02 -4.05997958e-03  2.85399882e+00
 -2.86843637e+00  5.92814778e+00 -7.26933458e-03 -9.68514157e-01
  1.71151128e-01 -9.39621540e-03 -3.92190926e-01  1.49056102e-02
 -4.16304471e-01]


<ipython-input-23-f512cf6c6716>:8: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  x, resid, rank, s = np.linalg.lstsq(X, y)
